/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author simon
 */
public class loginForm extends javax.swing.JFrame {

    Connection conn= null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    
    public loginForm() {
        initComponents();
        conn = MyConnection.getConnection();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idjname = new javax.swing.JLabel();
        idjpass = new javax.swing.JLabel();
        txtjname = new javax.swing.JTextField();
        txtjpass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        headerPanel.setBackground(new java.awt.Color(0, 0, 204));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sign Up !");
        headerPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        headerPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

        idjname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idjname.setText("Username :");

        idjpass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idjpass.setText("Password :");

        txtjname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtjname.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtjname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjnameActionPerformed(evt);
            }
        });

        txtjpass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtjpass.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtjpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjpassActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Forgotten");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Username / Password ?");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        btnlogin.setBackground(new java.awt.Color(0, 0, 204));
        btnlogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnlogin.setText("Log In");
        btnlogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnlogin.setBorderPainted(false);
        btnlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnloginMouseClicked(evt);
            }
        });
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 153, 51));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("     Create New Account");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        txtCombo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCombo.setForeground(new java.awt.Color(153, 153, 153));
        txtCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Owner", "Manager", "Head Accountant", "Senior Accountant", "Junior Accountant", "Charted Accountant", "Helper", "Dispatcher", "Quality Man", "Head Officer", "Head Sales Officer", "Checker", "Supervisor", "Head Packing Officer", " " }));
        txtCombo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtCombo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComboActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Designetion : ");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(btnlogin, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(txtjpass)
                            .addComponent(idjpass)
                            .addComponent(idjname)
                            .addComponent(txtjname)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(txtCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(idjname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtjname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(idjpass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtjpass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtjnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjnameActionPerformed

    private void txtjpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjpassActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMouseClicked
        // TODO add your handling code here:
        String uname = txtjname.getText();
        String pass = String.valueOf(txtjpass.getPassword());
        String designetion = txtCombo.getSelectedItem().toString();
        
        if(uname.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "User field is empty");
        }else if(pass.equals("")){
            JOptionPane.showMessageDialog(null, "Password field is empty");
        }else if(designetion.equals("")){
            JOptionPane.showMessageDialog(null, "Designetion field is empty");
        }else{
            
            try { 
                String query = "SELECT * FROM `user` WHERE `uname`=? AND `pass`=?";
                ps = conn.prepareStatement(query);
                ps.setString(1, uname);
                ps.setString(2, pass);
                
                rs = ps. executeQuery();
                
                if(rs.next()){
                    String name = rs.getString(3);
                    String des = rs.getString(5);
                    //String un = rs.getString("username");
                    //String s1 = rs.getString("designetion");
                    if(designetion.equalsIgnoreCase("Owner")&&des.equalsIgnoreCase("Owner")){
                        JOptionPane.showMessageDialog(null, "Login Successful");
                        mainForm m = new mainForm(name, des);
                        m.setVisible(true);
                        //setVisible(false);
                        this.dispose();
                    }
                    if(designetion.equalsIgnoreCase("Head Accountant")&&des.equalsIgnoreCase("Head Accountant")){
                        JOptionPane.showMessageDialog(null, "Login Successful");
                        mainForm1 cp = new mainForm1(name, des);
                        cp.setVisible(true);
                        setVisible(false);
                        this.dispose();
                    }
                    if(designetion.equalsIgnoreCase("Manager")&&des.equalsIgnoreCase("Manager")){
                        JOptionPane.showMessageDialog(null, "Login Successful");
                        mainForm1 cp = new mainForm1(name, des);
                        cp.setVisible(true);
                        setVisible(false);
                        this.dispose();
                    }
                    if(designetion.equalsIgnoreCase("Senior Accountant")&&des.equalsIgnoreCase("Senior Accountant")){
                        JOptionPane.showMessageDialog(null, "Login Successful");
                        mainForm1 cp = new mainForm1(name, des);
                        cp.setVisible(true);
                        setVisible(false);
                        this.dispose();
                    }
                    if(designetion.equalsIgnoreCase("Junior Accountant")&&des.equalsIgnoreCase("Junior Accountant")){
                        JOptionPane.showMessageDialog(null, "Login Successful");
                        mainForm1 cp = new mainForm1(name, des);
                        cp.setVisible(true);
                        setVisible(false);
                        this.dispose();
                    }
                    if(designetion.equalsIgnoreCase("Charted Accountant")&&des.equalsIgnoreCase("Charted Accountant")){
                        JOptionPane.showMessageDialog(null, "Login Successful");
                        mainForm1 cp = new mainForm1(name, des);
                        cp.setVisible(true);
                        setVisible(false);
                        this.dispose();
                    }
                    if(designetion.equalsIgnoreCase("Helper")&&des.equalsIgnoreCase("Helper")){
                        JOptionPane.showMessageDialog(null, "Login Successful");
                        mainForm1 cp = new mainForm1(name, des);
                        cp.setVisible(true);
                        setVisible(false);
                        this.dispose();
                    }
                    if(designetion.equalsIgnoreCase("Dispatcher")&&des.equalsIgnoreCase("Dispatcher")){
                        JOptionPane.showMessageDialog(null, "Login Successful");
                        mainForm1 cp = new mainForm1(name, des);
                        cp.setVisible(true);
                        setVisible(false);
                        this.dispose();
                    }
                    if(designetion.equalsIgnoreCase("Quality Man")&&des.equalsIgnoreCase("Quality Man")){
                        JOptionPane.showMessageDialog(null, "Login Successful");
                        mainForm1 cp = new mainForm1(name, des);
                        cp.setVisible(true);
                        setVisible(false);
                        this.dispose();
                    }if(designetion.equalsIgnoreCase("Head Sales Officer")&&des.equalsIgnoreCase("Head Sales Officer")){
                        JOptionPane.showMessageDialog(null, "Login Successful");
                        mainForm1 cp = new mainForm1(name, des);
                        cp.setVisible(true);
                        setVisible(false);
                        this.dispose();
                    }
                    if(designetion.equalsIgnoreCase("Head Officer")&&des.equalsIgnoreCase("Head Officer")){
                        JOptionPane.showMessageDialog(null, "Login Successful");
                        mainForm1 cp = new mainForm1(name, des);
                        cp.setVisible(true);
                        setVisible(false);
                        this.dispose();
                    }if(designetion.equalsIgnoreCase("Checker")&&des.equalsIgnoreCase("Checker")){
                        JOptionPane.showMessageDialog(null, "Login Successful");
                        mainForm1 cp = new mainForm1(name, des);
                        cp.setVisible(true);
                        setVisible(false);
                        this.dispose();
                    }
                    if(designetion.equalsIgnoreCase("Supervisor")&&des.equalsIgnoreCase("Supervisor")){
                        JOptionPane.showMessageDialog(null, "Login Successful");
                        mainForm1 cp = new mainForm1(name, des);
                        cp.setVisible(true);
                        setVisible(false);
                        this.dispose();
                    }
                    if(designetion.equalsIgnoreCase("Head Packing Officer")&&des.equalsIgnoreCase("Head Packing Officer")){
                        JOptionPane.showMessageDialog(null, "Login Successful");
                        mainForm1 cp = new mainForm1(name, des);
                        cp.setVisible(true);
                        setVisible(false);
                        this.dispose();
                    }
                    if(designetion.equalsIgnoreCase("Assembler")&&des.equalsIgnoreCase("Assembler")){
                        JOptionPane.showMessageDialog(null, "Login Successful");
                        mainForm1 cp = new mainForm1(name, des);
                        cp.setVisible(true);
                        setVisible(false);
                        this.dispose();
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Login Failed");
                    txtjname.setText("");
                    txtjpass.setText("");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_btnloginMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        signupForm s = new signupForm();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        forgotForm f = new forgotForm();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void txtComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComboActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel idjname;
    private javax.swing.JLabel idjpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JComboBox<String> txtCombo;
    private javax.swing.JTextField txtjname;
    private javax.swing.JPasswordField txtjpass;
    // End of variables declaration//GEN-END:variables
}
